packages:
  - apps/*
  - libs/*
  - '!**/test/**'
  - '!**/tests/**'
  - '!**/__tests__/**'
  - '!**/e2e/**'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - bcrypt
  - core-js-pure
  - esbuild
  - nx

onlyBuiltDependencies:
  - unrs-resolver
