packages:
  # All packages in direct subdirs of packages/
  - 'apps/*'
  - 'libs/*'
  # Exclude test directories
  - '!**/test/**'
  - '!**/tests/**'
  - '!**/__tests__/**'
  - '!**/e2e/**'

# Ignore build scripts for these packages to prevent postinstall issues
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - bcrypt
  - core-js-pure
  - esbuild
  - nx
